/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"

int
main (int argc, char *argv[])
{
  GtkWidget *ajouter_ouvrier;
  GtkWidget *liste_des_ouvriers;
  GtkWidget *Pointage_ouvrier;
  GtkWidget *Modifier_ouvrier;
  GtkWidget *alerte;
  GtkWidget *operation_reussie;
  GtkWidget *operation_non_reussie;

#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory (PACKAGE_DATA_DIR "/" PACKAGE "/pixmaps");

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
  ajouter_ouvrier = create_ajouter_ouvrier ();
  gtk_widget_show (ajouter_ouvrier);
  liste_des_ouvriers = create_liste_des_ouvriers ();
  gtk_widget_show (liste_des_ouvriers);
  Pointage_ouvrier = create_Pointage_ouvrier ();
  gtk_widget_show (Pointage_ouvrier);
  Modifier_ouvrier = create_Modifier_ouvrier ();
  gtk_widget_show (Modifier_ouvrier);
  alerte = create_alerte ();
  gtk_widget_show (alerte);
  operation_reussie = create_operation_reussie ();
  gtk_widget_show (operation_reussie);
  operation_non_reussie = create_operation_non_reussie ();
  gtk_widget_show (operation_non_reussie);

  gtk_main ();
  return 0;
}

